#!/usr/bin/env ruby
# frozen_string_literal: true

require 'net/http'
require 'json'

API_KEY = ENV.fetch('AE_TEST_COVERAGE_API_KEY') do
  puts 'API key is required. Example `export AE_TEST_COVERAGE_API_KEY=your-api-key`'
  exit
end

HOST = "http://host.docker.internal:3000"

uri = URI.parse("#{HOST}/api/v1/repository")
headers = {'Content-Type': 'application/json', 'X-API-KEY' => API_KEY}

# Create the HTTP objects
http = Net::HTTP.new(uri.host, uri.port)
request = Net::HTTP::Get.new(uri.request_uri, headers)

# Send the request
response = http.request(request)

body = JSON.parse(response.body)
git_branch = body["default_branch_name"]



diff = `git diff #{git_branch}`

uri = URI.parse("#{HOST}/api/v1/call_graphs/tests_from_diff")
headers = {'Content-Type': 'application/json', 'X-API-KEY' => API_KEY}

request_body = {
  git_branch: git_branch,
  diff: diff
}

# Create the HTTP objects
http = Net::HTTP.new(uri.host, uri.port)
request = Net::HTTP::Post.new(uri.request_uri, headers)
request.body = request_body.to_json

# Send the request
response = http.request(request)
body = JSON.parse(response.body)

puts body['tests'].join(' ')