#!/usr/bin/env ruby
# frozen_string_literal: true

require "selective"

body = Selective::Api.request("repository", method: :get)

git_branch = body["default_branch_name"]

`git fetch origin #{git_branch}`

diff = `git diff origin/#{git_branch}`

request_body = {
  git_branch: git_branch,
  diff: diff
}

body = Selective::Api.request("call_graphs/tests_from_diff", request_body, method: :post)

puts body["tests"].join(" ")
