#!/usr/bin/env ruby
# frozen_string_literal: true

require "net/http"
require "json"

body = Api.request('repository')

git_branch = body["default_branch_name"]

diff = `git diff #{git_branch}`

request_body = {
  git_branch: git_branch,
  diff: diff
}

body = Api.request('call_graphs/tests_from_diff', request_body)

puts body["tests"].join(" ")
