name: CI
on: [push]

env:
  GIT_BRANCH: ${{ github.ref }}
  GIT_COMMIT_SHA: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: No Docs
      run: "echo 'gem: --no-document' >> ~/.gemrc"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: RubyGems Update
      run: gem update --system
    - name: Bundle Install
      run: bundle install
    
    - name: Set ENV for codeclimate
      run: |
        echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-env name=GIT_COMMIT_SHA::$GITHUB_SHA"
      if: github.event_name == 'push'

    - name: Prepare install CodeClimate Test Reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    
    - name: RSpec
      run: |
        bundle exec rspec --format progress \
                          --format RspecJunitFormatter \
                          --out /tmp/test-results/rspec.xml \
                          --format progress

        ./cc-test-reporter format-coverage -t simplecov $GITHUB_WORKSPACE/coverage/.resultset.json
        ./cc-test-reporter upload-coverage